django_project/core/urls.py
# from django.conf.urls import patterns, include, url
#
# from django.contrib import admin
# admin.autodiscover()
#
# urlpatterns = patterns('',
#    # Examples:
#    # url(r'^$', 'django_project.views.home', name='home'),
#    # url(r'^blog/', include('blog.urls')),
#
#    url(r'^admin/', include(admin.site.urls)),
# )
from __future__ import unicode_literals

from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from mezzanine.core.views import direct_to_template

admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns(
    '',

    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    ("^admin/", include(admin.site.urls)),

    # For mezzanine-people
    ("^people/", include('mezzanine_people.urls')),
    ("^api/people/", "core.views.get_all_people"),
    # Mezzanine Careers
    ("^careers/", include("careers.urls")),
    ("^map/", include("wms_client.urls")),
    # For cartridge, the mezzanine ecommerce platform.
    ("^shop/", include("cartridge.shop.urls")),
    ("^payment/", include("payment.urls")),
    url("^account/orders/$", "cartridge.shop.views.order_history",
        name="shop_order_history"),

    ("^clients/", include('clients.urls')),

    # For mezzanine-agenda
    ("^%s/" % settings.EVENT_SLUG, include("mezzanine_agenda.urls")),

    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    # url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.

    url("^$", "mezzanine.pages.views.page", {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings/contrib.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.

    # url("^$", "mezzanine.blog.views.blog_post_list", name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

    # For mezzanine-agenda
    ("^%s/" % settings.EVENT_SLUG, include("mezzanine_agenda.urls")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

django_project/clients/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from mezzanine.core.fields import RichTextField, FileField
from mezzanine.core.models import Displayable, RichText, Slugged
from mezzanine.utils.models import AdminThumbMixin

__author__ = 'Dimas Ciputra <dimas@kartoza.com>'
__date__ = '07/09/16'


class Client(Displayable, RichText, AdminThumbMixin):
    """A client model"""
    name = models.CharField(
        help_text=_('Name of the client.'),
        max_length=255,
        null=False,
        blank=False,
    )

    link = models.URLField(
        help_text=_('Client company site link'),
        max_length=255,
        blank=False,
        null=False,
    )

    logo = FileField(
        verbose_name=_("Client logo image"),
        upload_to="client",
        format="Image",
        max_length=255,
        null=False
    )

    class Meta:
        """Meta class for client."""
        verbose_name = _("Clients")
        verbose_name_plural = _("Client")
        ordering = ("name", "link", "logo", "description")

    @models.permalink
    def get_absolute_url(self):
        return "client_detail", (), {"slug": self.slug}

django_project/flat_theme/views.py
from django.shortcuts import render

# Create your views here.

django_project/flat_theme/templates/generic/includes/comment.html
{% load i18n mezzanine_tags comment_tags rating_tags %}

{% for comment in comments_for_thread %}

<div id="comment-{{ comment.id }}"
    class="comment media{% if comment.by_author %} comment-author{% endif %}">
	
    {% editable comment.is_public comment.is_removed %}
    {% if not comment.is_removed and comment.is_public or request.user.is_staff %}
    {% if comment.url %}
       <div class="pull-left">
											   
											
		<a href="{{ comment.url }}">
			<img class="avatar img-circle" src="{% gravatar_url comment.email %}">
		</a>
    </div>
    <div class="media-body">
		<div class="well">
        
        <div class="media-heading">
                <strong><a href="{{ comment.url }}">{{ comment.user_name }}</a></strong>&nbsp; 
                <small>{% blocktrans with sometime=comment.submit_date|timesince %}{{ sometime }} ago{% endblocktrans %}</small>
                     {% if not comment.is_removed and comment.is_public %}
                      <a href="#reply-{{ comment.id }}" class="pull-right reply"><i class="icon-repeat"></i> {% trans "Reply" %}</a>
                     
                       {% endif %}
         </div>
    {% else %}
    <div class="pull-left">
											   
											
		<a href="{{ comment.url }}">
			<img class="avatar img-circle" src="{% gravatar_url comment.email %}">
		</a>
    </div>
    <div class="media-body">
		<div class="well"> 
        <div class="media-heading">
                <strong><a href="{{ comment.url }}">{{ comment.user_name }}</a></strong>&nbsp; 
                
    {% endif %}
           <small>{% blocktrans with sometime=comment.submit_date|timesince %}{{ sometime }} ago{% endblocktrans %}</small>
                     {% if not comment.is_removed and comment.is_public %}
                      <a href="#reply-{{ comment.id }}" class="pull-right reply"><i class="icon-repeat"></i> {% trans "Reply" %}</a>
                     
                       {% endif %}
         </div>
    <p>{{ comment.comment|comment_filter }}</p>
    {% endif %}
    
    {% if not comment.is_removed and comment.is_public %}
    <a href="{{ request.path }}#comment-{{ comment.id }}">
        <span class="glyphicon glyphicon-link"></span> {% trans "Link" %}
    </a> 
    
    {% if settings.COMMENTS_USE_RATINGS %}
    <div class="rating">
    {% rating_for comment %}
    </div>
    {% endif %}
    </div>
    <form class="comment-reply-form" method="post" id="reply-{{ comment.id }}"
        action="{{ comment_url }}#reply-{{ comment.id }}"
        {% if replied_to != comment.id %}style="display:none;"{% endif %}>
        {% if replied_to == comment.id %}
        {% fields_for posted_comment_form %}
        {% else %}
        {% fields_for unposted_comment_form %}
        {% endif %}
        <input type="hidden" name="replied_to" value="{{ comment.id }}">
        <input class="btn btn-primary btn-lg" type="submit" value="{% trans "Reply" %}">
    </form>

    {% else %}
    <p>
        {% if comment.is_removed %}
        <span class="glyphicon glyphicon-remove-circle"></span> {% trans "Comment deleted" %}
        {% else %}
        <span class="glyphicon glyphicon-warning-sign"></span> {% trans "Comment awaiting approval" %}
        {% endif %}
        <small class="timespan">{% blocktrans with sometime=comment.submit_date|timesince %}{{ sometime }} ago{% endblocktrans %}</small>
    </p>
    {% endif %}

    {% comment_thread comment %}
    
    {% if not comment.is_removed and comment.is_public or request.user.is_staff %}</div>{% endif %}
    {% endeditable %}
</div>

{% endfor %}

{% if no_comments %}
<p>{% trans "There are currently no comments" %}</p>
{% endif %}

django_project/flat_theme/templates/generic/includes/comment_form.html
{% load i18n mezzanine_tags comment_tags %}

<form method="post" id="contactform" action="{{ comment_url }}#comment" class="form-horizontal" role="form">
   {% csrf_token %}
	{% for hidden in comment_form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
	
	<div class="form-group">
		<div class="col-sm-4">
			<input type="text" value="{{comment_form.name.value}}" name="name" id="id_name"  placeholder="* Enter your full name" class="form-control" >
		</div>
		<div class="col-sm-4">
			<input type="email" value="{{comment_form.email.value}}" name="email" id="id_email" placeholder="* Enter your email address" class="form-control">
		</div>
		<div class="col-sm-4">
		   <input type="url" value="" name="{{comment_form.url.value}}" id="id_url" placeholder="Enter your webiste" class="form-control">
		</div> 
    </div>
	<div class="form-group">
		<div class="col-sm-12">
			
			<textarea rows="8" name="comment" id="id_comment"  class="form-control" placeholder="* Enter Comment here..."></textarea>
		</div>
    </div>
	<button class="btn btn-danger btn-lg" type="submit">Submit Comment</button>
</form>

django_project/flat_theme/templates/generic/includes/comments.html
{% load i18n mezzanine_tags comment_tags %}
<div id="comments">
	
<h3>{% trans "Comments" %}</h3>
<div class="comments-list">
{% if settings.COMMENTS_DISQUS_SHORTNAME %}
{% include "generic/includes/disqus_comments.html" %}
{% else %}
<script>
$(function() {
    $('.reply').click(function() {
        $('.comment-reply-form').hide();
        $(this).parent().parent().siblings('.comment-reply-form').toggle();
    });
});
</script>
<style>.input_id_honeypot {display:none !important;}</style>
{% comment_thread object_for_comments %}

{% endif %}
</div>
<div id="comment-form">
<h3>{% trans "New Comment" %}</h3>

{% if not request.POST.replied_to %}
		{% include "generic/includes/comment_form.html" with comment_form=posted_comment_form %}
    {% else %}
    {{% include "generic/includes/comment_form.html" with comment_form=unposted_comment_form %}
    {% endif %}


</div>
</div>

django_project/flat_theme/templates/generic/includes/disqus_comments.html
{% load disqus_tags %}

<div id="disqus_thread"></div>
{% disqus_sso_script %}
<script>
    var disqus_developer = '{{ settings.DEV_SERVER }}' == 'True';
    var disqus_url = 'http{% if request.is_secure %}s{% endif %}://{{ request.META.HTTP_HOST }}{{ object_for_comments.get_absolute_url }}';
    var disqus_title = '{{ object_for_comments|escapejs }}';
    var disqus_identifier = '{% disqus_id_for object_for_comments %}';
  (function() {
   var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
   dsq.src = 'http{% if request.is_secure %}s{% endif %}://{{ settings.COMMENTS_DISQUS_SHORTNAME }}.disqus.com/embed.js';
   (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>

django_project/flat_theme/templates/generic/includes/disqus_counts.html
<script>
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = '{{ settings.COMMENTS_DISQUS_SHORTNAME }}'; // required: replace example with your forum shortname

/* * * DON'T EDIT BELOW THIS LINE * * */
(function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = '//' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>

django_project/flat_theme/templates/generic/includes/disqus_sso.html
<script>
var disqus_config = function () {
    this.page.remote_auth_s3 = '{{ sso_data }}';
    this.page.api_key = '{{ public_key }}';
}
</script>

django_project/flat_theme/templates/generic/includes/rating.html
{% load mezzanine_tags rating_tags i18n future %}

<span id="rating-{{ rating_object.id }}">
    {% if rating_average %}
    {% trans "Current rating" %}: {{ rating_average|floatformat }}
    {% else %}
    {% trans "Currently unrated" %}
    {% endif %}
</span>

{% if not rated or request.user.is_authenticated %}
<form class="form-inline" role="form" method="post" action="{% url "rating" %}">
    {% nevercache %}
    {% csrf_token %}
    {% endnevercache %}
    <ul class="radio radio-inline">{{ rating_form.as_ul }}</ul>
    <input type="submit" class="btn btn-default btn-sm" value="{% trans "Rate" %}"
        onclick="return $(this.form).find('input:checked').length == 1;">
</form>
{% endif %}